### ISSUE TITLE
Bindings for wasm_export.h and OOP

### ISSUE THREAD

**Issue by tonibofarull** [bytecodealliance/wamr-python#8]
Hi,
I'm working on creating the Python bindings for [wasm_export.h](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/iwasm/include/wasm_export.h) to be able to use all WAMR's features and not be restricted to wasm-c-api (e.g., debugger or WASI). Do you think it makes sense to post them here?

Regarding an OOP implementation, is https://github.com/bytecodealliance/wamr-python/blob/main/examples/hello_oop.py something definitive, or is it open for proposals?

**Comment by wenyongh** [comment]
No, we have merged this feature into WAMR repo, could you please change the code based on:
https://github.com/bytecodealliance/wasm-micro-runtime/tree/main/language-bindings/python
and upload the PR? Many thanks!

**Comment by wenyongh** [comment]
> 
> Regarding an OOP implementation, is https://github.com/bytecodealliance/wamr-python/blob/main/examples/hello_oop.py something definitive, or is it open for proposals?

Yes, it is open, you can enhance this file or add other sample files.

**Comment by tonibofarull** [comment]
One last question @wenyongh, why this repo is still alive if the bindings are merged into WAMR?
